# Generated by Django 4.1.5 on 2023-05-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_audio',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
