# Generated by Django 4.1.5 on 2023-02-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_writer_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
