# Generated by Django 4.1.5 on 2023-07-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='saved_articles',
            field=models.ManyToManyField(blank=True, related_name='saved_articles', to='blog.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='article_likes', to='blog.writer'),
        ),
    ]
