# Generated by Django 4.1.5 on 2023-02-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_writer_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-update_date']},
        ),
    ]
