# Generated by Django 4.1.5 on 2023-04-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_reply_replied_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.reply'),
        ),
    ]
