# Generated by Django 4.1.5 on 2023-02-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_url',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
