# Generated by Django 4.1.5 on 2023-02-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='display_email',
            field=models.BooleanField(default=False),
        ),
    ]
