# Generated by Django 4.1.5 on 2023-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_writer_display_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
