# Generated by Django 4.1.5 on 2023-02-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_writer_linkedin_url_writer_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_audio',
            field=models.FileField(default=1, upload_to='article_audio/'),
            preserve_default=False,
        ),
    ]
